# Generated by Django 2.1.7 on 2019-04-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='image',
            field=models.ImageField(null=True, upload_to='image/%Y%m%d'),
        ),
    ]
